#!/usr/bin/env python
import argparse


from buildaspider import Spider


if __name__ == '__main__':
    desc = """Not all those who wander are lost..."""

    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument(
        '-c', 
        '--config',
        help='Absolute path to config file.', 
        required=True, 
        type=str,
    )
    parser.add_argument(
        '-v', 
        '--verbose', 
        help='Enable verbose mode.', 
        required=False, 
        action="store_true"
    )
    parser.add_argument(
        '-w', 
        '--workers', 
        help='Specify max number of concurrent workers.', 
        required=False, 
        type=int, 
        default=8
    )

    args = parser.parse_args()

    crawler = Spider(
        args.config, 
        verbose=args.verbose, 
        max_workers=args.workers,
    )

    crawler.status_logger.info(
        f"Crawling started. (max_workers={args.workers})"
    )

    crawler.run()
